### ISSUE TITLE
Formatting doesn't work

### ISSUE THREAD

**Issue by Metallizzer** [SergeyKasyanov/vscode-october-extension#17]
Hello

October Code v0.28.00
An error occurs when trying to format code

`2024-06-25 19:27:51.247 [error] [Extension Host] Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
    at Fn (/home/metallizzer/.vscode/extensions/sergeykasyanov.october-code-0.28.0/dist/extension.js:2:939448)
    at Pn (/home/metallizzer/.vscode/extensions/sergeykasyanov.october-code-0.28.0/dist/extension.js:2:940562)
    at qn (/home/metallizzer/.vscode/extensions/sergeykasyanov.october-code-0.28.0/dist/extension.js:2:946406)
    at Jn (/home/metallizzer/.vscode/extensions/sergeykasyanov.october-code-0.28.0/dist/extension.js:2:948994)
    at Object.Dr (/home/metallizzer/.vscode/extensions/sergeykasyanov.october-code-0.28.0/dist/extension.js:2:952664)
    at t.formatTwig (/home/metallizzer/.vscode/extensions/sergeykasyanov.october-code-0.28.0/dist/extension.js:2:1297214)
    at t.OctoberTplDocumentFormatting.provideDocumentFormattingEdits (/home/metallizzer/.vscode/extensions/sergeykasyanov.october-code-0.28.0/dist/extension.js:2:1299223)
    at F.provideDocumentFormattingEdits (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:107334)
`

**Comment by SergeyKasyanov** [comment]
Hello. Thanks for reporting. Try new version 0.28.1

**Comment by Metallizzer** [comment]
> Hello. Thanks for reporting. Try new version 0.28.1

Thanks. It works now
Can you please look at #14 issue
